# Generated by Django 5.1.2 on 2024-11-07 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=5)),
                ('company_name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_date_time', models.DateTimeField()),
                ('last_login_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation_type', models.CharField(max_length=100)),
                ('generated_time', models.DateTimeField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('volume', models.IntegerField()),
                ('stock_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock')),
            ],
        ),
    ]
