# Generated by Django 5.1.2 on 2025-01-16 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_stock_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='total_buy_signals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='total_hold_signals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='total_sell_signals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='ticker',
            field=models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='stock.stock'),
        ),
    ]
