# Generated by Django 5.1.2 on 2025-01-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_recommendations_total_buy_signals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='price_change',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='price_change_percent',
            field=models.FloatField(null=True),
        ),
    ]
