# Generated by Django 5.1.2 on 2025-01-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stockdata_price_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='total_buy_signals',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='total_hold_signals',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='total_sell_signals',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='last_200_close_prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='price_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='price_change_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strategies',
            name='bollinger_bands',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='strategies',
            name='moving_averages',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='strategies',
            name='rsi',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
