# Generated by Django 5.1.2 on 2025-01-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_recommendations_total_buy_signals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendations',
            name='total_buy_signals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='total_hold_signals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='total_sell_signals',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
